<Project Sdk="Aspire.AppHost.Sdk/13.5.0">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>3e4f8198-1258-4c3f-8be5-6de3d7a005b1</UserSecretsId>

		<Product>ServiceBusViewer</Product>
		<Authors>Andrey Veselov</Authors>
		<Copyright>Copyright © 2025-2026 Andrey Veselov</Copyright>

		<AnalysisLevel>latest</AnalysisLevel>
		<AnalysisLevel>10.0-recommended</AnalysisLevel>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.JavaScript" Version="13.5.0" />
		<PackageReference Include="Aspire.Hosting.Azure.ServiceBus" Version="13.5.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ServiceBusViewer\ServiceBusViewer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SolidCode.Aspire.Hosting.ServiceBusViewer\SolidCode.Aspire.Hosting.ServiceBusViewer.csproj" IsAspireProjectResource="false" />
	</ItemGroup>

	<ItemGroup>
		<None Update="ServiceBusConfig.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
