<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>0.20.0</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<Product>ServiceBusViewer</Product>
		<Authors>Andrey Veselov</Authors>
		<Copyright>Copyright © 2025-2026 Andrey Veselov</Copyright>
		<Description>HTTP API for the Service Bus Viewer.</Description>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
	</ItemGroup>

</Project>
