<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<Product>ServiceBusViewer</Product>
		<Version>0.48.0</Version>
		<Authors>Andrey Veselov</Authors>
		<Copyright>Copyright © 2025-2026 Andrey Veselov</Copyright>
		<Description>HTTP API for the Service Bus Viewer.</Description>

		<AnalysisLevel>10.0-recommended</AnalysisLevel>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>

		<!-- Disable warning CA1848:Use the LoggerMessage delegates. Reason: Logging performance optimization is not required for this project. -->
		<NoWarn>$(NoWarn);CA1848</NoWarn>

		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\" />
	</ItemGroup>

	<Target Name="EnsureWwwrootExists" BeforeTargets="PrepareForBuild" Condition="!Exists('$(ProjectDir)wwwroot')">
		<MakeDir Directories="$(ProjectDir)wwwroot" />
	</Target>

</Project>
