name: Build and publish the canary container images

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]
    paths:
    - '.dockerignore'
    - 'src/ServiceBusViewer/**'
    - 'src/ServiceBusViewer.Web/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
        - image_name: ServiceBusViewer
          dockerfile: ./src/ServiceBusViewer/Dockerfile
        - image_name: servicebusviewer-web
          dockerfile: ./src/ServiceBusViewer.Web/Dockerfile

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v7
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ghcr.io/veselovandrey/${{ matrix.image_name }}:canary
