name: Build and publish the canary container image

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]
    paths:
    - '.dockerignore'
    - 'package.json'
    - 'package-lock.json'
    - 'scripts/**'
    - 'src/ServiceBusViewer/**'

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v7
      with:
        context: .
        file: ./src/ServiceBusViewer/Dockerfile
        push: true
        tags: |
          ghcr.io/veselovandrey/servicebusviewer:canary
