name: Build and publish the canary container image

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]
    paths:
    - '.dockerignore'
    - 'src/ServiceBusViewer/**'
    - '!src/ServiceBusViewer/**/*.md'
    - 'src/ServiceBusViewer.Web/**'
    - '!src/ServiceBusViewer.Web/**/*.md'
    - 'src/ServiceBusViewer.UnitTests/**'
    - 'src/ServiceBusViewer.ArchitecturalTests/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'

    - name: Run unit tests
      run: dotnet test --project ./src/ServiceBusViewer.UnitTests --configuration Debug

    - name: Run architecture tests
      run: dotnet test --project ./src/ServiceBusViewer.ArchitecturalTests --configuration Debug

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v7
      with:
        context: .
        file: ./src/ServiceBusViewer/Dockerfile
        push: true
        tags: ghcr.io/veselovandrey/servicebusviewer:canary
